# -*- coding: utf-8 -*-
"""lab2_release.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmYdQ6nHlf0T2yKR6R_e_UCnUhQsHhDS

# General instructions for all labs

1. To turn in:
 - this python notebook, filled out (2 pts)
 - a *standalone* PDF report that contains all the plots, and the answers to all the discussion questions (2 pts)

2. Use of ChatGPT / CoPilot / etc:
   - Allowed, but you own everything that is generated
   - This means that any part of the solution can be asked in the quiz. It can be as detailed as "What was the batch size you used in training" or specific as "what exactly does masking do in this case?" Any discussion question is also game for a quiz question.
   - If I find AI usage to be excessive. I can individually drag any of you in for a 1-1 meeting, in which I grill you on your code. If it looks like irresponsible copy/pasting, without proper understanding, I reserve the right to drastically lower your grade, or even submit cases to GGAC for ethical review.
  
3. Use of peer collaboration:
   - In general not allowed. (Discussion / comparing answers is ok, but work on actual coding independently.)
   - Exceptions can be made if you all wrote your own training script, but 1. it takes forever to train or 2. you don't have great compute resources. Then you can share a trained model amongst yourself *and declare it on your pdf*. However, the code for training *still must be written by yourself*

# Lab 2: RAG over a Large Codebase

## SciPy

**SciPy** is a fundamental open-source library for scientific computing in Python. It builds on top of **NumPy** and provides efficient implementations of many core algorithms for mathematics, science, and engineering. SciPy is widely used in academia and industry for numerical analysis, optimization, signal processing, and more.

### Key Features

* **Linear Algebra & Optimization:** Robust solvers for systems of equations, eigenvalue problems, and constrained/unconstrained optimization.  
* **Integration & Differential Equations:** Tools for numerical integration, ODE solvers, and quadrature.  
* **Signal & Image Processing:** Filtering, Fourier transforms, and image manipulation utilities.  
* **Statistics & Probability:** Random variables, hypothesis testing, and statistical distributions.  
* **Sparse Matrices:** Efficient storage and computation with large, sparse systems.  

SciPy underlies much of the Python scientific ecosystem, serving as the backbone for applications in physics, biology, engineering, data science, and machine learning.

### Resources

* 📖 [Documentation](https://docs.scipy.org/doc/scipy/)  
* 💻 [GitHub Repository](https://github.com/scipy/scipy)

---

## Lab Goal

In this lab, you will build a **Retrieval-Augmented Generation (RAG) system** to answer natural language questions about a debase (\~10,000 scripts). By combining a L and a RAG over the del (Ldocumentation and LM) rieved SciPy should help a newbie coder the system will help you explore and understand complex source code, algorithms, and APIs.

#

## Part 1 – Setup and Preprocessing

In this part, you will complete the following. The notebook will walk you through it step by step.

1. **Documentation Preparation**

   * Obtain the provided project documentation (manuals, reference guides, tutorials, etc.).
   * Each section will be treated as text input for retrieval.
   * Ignore large binary files, images, and other non-text resources.

2. **Chunking**

   * Split the documentation into overlapping chunks:

     * Suggested: 300–500 tokens per chunk.
     * Overlap: 50–100 tokens to preserve context across boundaries.
   * Store metadata for each chunk, such as document name and section or page reference.

3. **Embedding Generation**

   * Use a sentence-transformer (e.g., `msmarco-distilbert-base-v3`) to generate embeddings for each chunk of documentation.
   * Save embeddings and metadata to disk for reuse.

4. **Vector Database**

   * Load embeddings into FAISS or Chroma.
   * Confirm you can perform a similarity search for a sampmake the flow of the lab smoother.

### Part 1 Step 1: Expanding Code Comments

Take a look at each of these helper scripts. To demonstrate you fully understand the code, you will expand the comments.   The comments should explain not only *what* each line of code does, but also *why* it is there and *how* it contributes to the larger goal of the pipeline.

You are welcome to use ChatGPT (or other tools) to help generate initial drafts of comments. However, you are ultimately responsible for understanding the details — you will be expected to **regurgitate this level of explanation on an exam without assistance**.
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/Courses/CSE 519/Lab 2'

!apt install libomp-dev
!pip install faiss-cpu

import os
import json
import faiss
import numpy as np
from pathlib import Path
from typing import List, Dict

import torch
from transformers import AutoTokenizer, AutoModel

from sentence_transformers import SentenceTransformer
models = {}
#models['code'] = SentenceTransformer("sentence-transformers/msmarco-distilbert-base-v3")
models['code'] = SentenceTransformer("BAAI/bge-m3")

models['docs'] = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# -------- 1. File Loader --------
def load_code_files(base_dir, exts={".cpp", ".h", ".c", ".f90", ".py"}):
    """
    What does it do? (1 sentence)
    This function searches for and loads files with specific
    extensions from a given directory and its subdirectories, creating a
    generator function that returns the file path and its content.

    What are the inputs?
    base_dir: The root directory to start the search from. This is a required
    input.
    exts: The set of file extensions to look for. This is an optional input but
    has a default value of extensions {".cpp", ".h", ".c", ".f90", ".py"}.

    What are the outputs?
    The output is a generator function that yields a tuple in the form
    (full path of file, content of file) for each matching file extension
    it finds.

    """
    for root, _, files in os.walk(base_dir):
        for f in files:
            if os.path.splitext(f)[-1] in exts:
                try:
                    path = Path(root) / f
                    with open(path, "r", errors="ignore") as fh:
                        yield str(path), fh.read()
                except Exception as e:
                    print(f"Skipping {f}: {e}")


# -------- 2. Chunker --------
def chunk_text(text: str, chunk_size=1000, overlap=0):
    """
    What does it do? (1 sentence)
    The function splits the given text into smaller, overlapping chunks based
    upon the word count of the text.

    What are the inputs?
    text: This is a string representing the string text to chunk. This is a
    required input.
    chunk_size: The size of the chunk in words. This is an optional input with
    value 1000.
    overlap: The number of words that overlap between the current and the previous
    chunk. This is an optional input with default value 0.

    What are the outputs?
    The output is a list of dictionaries with 3 keys: text, start_word, and
    end_word. Simply, text is the content of the chunk as a string.
    start_word is the starting word index of the chunk in the original text.
    end_word is the ending word index of the chunk in the original text.

    """
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        piece = " ".join(words[i:i+chunk_size])
        if piece.strip():
            chunks.append({
                "text": piece,
                "start_word": i,
                "end_word": i+chunk_size
            })
    return chunks


# -------- 3. Embedding with CodeBERT --------
def embed_texts(model, texts):
    """
    What does it do? (1 sentence)
    The function takes a pre-trained transformer model (in this case
    CodeBERT) and a list of texts and encodes the texts into numerical vector
    representations based upon the model.

    What are the inputs?
    model: A pre-trained transformer model. This is a required input.
    texts: A list of strings that need to be converted into embeddings. Each
    element of the list is a single text. This is a required input.

    What are the outputs?
    embs: A NumPy array containing the embeddings of the text. They are of size
    (number of texts, embedding_dimension), with embedding_dimension to be
    determined by the input model.

    """
    embs = model.encode(
        texts,
        batch_size=16,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True  # good for cosine similarity
    )
    return embs

"""

## FAISS

The next two code blocks introduce **FAISS** (Facebook AI Similarity Search), a library built for efficient similarity search across large collections of vectors. After we embed documentation chunks into high-dimensional vectors, FAISS gives us the data structures and algorithms needed to store them and quickly retrieve the closest matches to a query.

A key feature of FAISS is its support for different types of **indexes** for vector search. In this lab, we will start with the simplest option: **IndexFlatL2**.

* This index stores all vectors directly in memory.
* It computes exact Euclidean ($L^2$) distances for each query.
* It is best suited for datasets ranging from a few thousand up to a few hundred thousanke HNSW or IVF?
"""

# -------- 4. Build Vector DB --------
def build_faiss_index(chunks_with_meta, dim):
    """
    What does it do? (1 sentence)
    This function takes a list of chunks with their embeddings and builds
    a FAISS index.

    What are the inputs?
    chunks_with_meta: A list of dictionaries, where each dictionary represents
    a chunk and contains an embedding for the text in the chunk. This is a
    required input.
    dim: The dimensions of the embeddings, which should match the dimensions
    of the embeddings in the chunks_with_meta input. This is a required input.

    What are the outputs?
    The function returns a FAISS index object.

    """
    index = faiss.IndexFlatL2(dim)
    embeddings = np.vstack([c["embedding"] for c in chunks_with_meta]).astype("float32")
    index.add(embeddings)
    return index



# -------- Example Query --------
def query_index(query, topk=5, code_or_doc = 'code'):
    """
    What does it do? (1-2 sentences)
    This function takes a query and a FAISS index and performs a
    similarity search to find the most relevant code or documentation snippets.
    It returns the indices of the top-ranked results from the vector database.

    What are the inputs?
    query: The user's input string. This is a required input.
    topk: The number of top results to retrieve. This is an optional input
    with default value 5.
    code_or_doc: A string to specify whether to check the code chunks or the
    documentation chunks. This is an optional argument with default value
    'code'.

    What are the outputs?
    This function outputs a NumPy array of the indices of the topk most similar
    chunks in the FAISS index. This can help retrieve the original text from the
    chunk indices.

    """

    index = faiss.read_index("%s/code_chunks.index" % code_or_doc)

    q_emb = embed_texts(models[code_or_doc],[query]).astype("float32")

    distances, indices = index.search(q_emb, topk)

    return indices[0]

# -------- MAIN PIPELINE --------
def process_codebase(base_dir="scipy-main", code_or_doc = 'code'):
    all_chunks = []
    if code_or_doc == 'docs':
        exts = {'.rst'}
        chunk_size = 1000
    else:
        exts = {'.py'}
        chunk_size = 250
    for fpath, text in load_code_files(base_dir, exts):
        for chunk in chunk_text(text,chunk_size=chunk_size):
            chunk["file"] = fpath
            all_chunks.append(chunk)

    # Embed with CodeBERT
    texts = [c["text"] for c in all_chunks]

    embs = embed_texts(models[code_or_doc], texts)
    print('done with embed')
    for c, e in zip(all_chunks, embs):
        c["embedding"] = e

    # Save metadata
    with open("%s/chunks_metadata.json" % code_or_doc, "w") as out:
        for c in all_chunks:
            meta = {k: v for k, v in c.items() if k != "embedding"}
            out.write(json.dumps(meta) + "\n")

    # Build index

    dim = len(all_chunks[0]["embedding"])
    index = build_faiss_index(all_chunks, dim)
    faiss.write_index(index, "%s/code_chunks.index" % code_or_doc)
    print(f"Processed {len(all_chunks)} chunks from {base_dir}.")


process_codebase("scipy-main/doc/source",code_or_doc = 'docs')   # run once for docs
process_codebase("scipy-main/scipy",code_or_doc = 'code')   # run once for code

"""## Part 2: Testing

Now that you have built a vector-based retrieval tool on the **SciPy documentation**, the next step is to **qualitatively assess how well it works**. You will not compute numerical accuracy yet. Instead, you will explore retrieval behavior and record your judgments about when the system feels useful, misleading, or irrelevant.

You will use two supports for this process:

1. The **official SciPy documentation** (provided in the lab).
2. A **free ChatGPT interface** to act as an external “relevance judge.”

---

### 1. Design a Variety of Queries

Create at least **5 queries** covering different types of information you might want from SciPy. Use the templates below and adapt them to optimization, statistics, linear algebra, and sparse matrices:

* **Conceptual (high-level):**
  Ask about an algorithm, method, or mathematical concept.
  *Example:* `"trust-region methods in optimization"` or `"sparse matrix factorization"`.

* **Function/API-specific:**
  Target a known function, class, or module in SciPy.
  *Example:* `"scipy.optimize.minimize"` or `"scipy.sparse.linalg.cg"`.

* **Keyword-only:**
  Use just a technical term.
  *Example:* `"Poisson distribution"` or `"LU decomposition"`.

* **Natural language (descriptive):**
  Ask a full question in plain English.
  *Example:* `"How do I compute confidence intervals for a normal distribution in SciPy?"`

* **Edge cases:**
  Include queries that are vague, misspelled, or off-topic.
  *Example:* `"optimizashun"`, `"solver"`, `"deep learning"`.

---

### 2. Compare with the Manual

For each query:

1. Look up the topic in the SciPy documentation (using search or Ctrl+F).
2. Compare the retrieved snippets with the official docs.

   * If they match or are consistent, mark as **aligned**.
   * If they do not appear in the docs, mark as **potentially irrelevant**.

This provides a rough ground truth based on trusted documentation.

---

### 3. Use ChatGPT as a Relevance Judge

For an additional check, you will ask ChatGPT whether each retrieved snippet is relevant to the query. Use a **standardized prompt template** to keep your experiments consistent.

**Template:**rence (optional): [short excerpt from SciPy documentation]  

Question for ChatGPT:  
"Is this snippet relevant to the query? Answer Yes or No, and provide a one-sentence justification."  
```

**Example:**

```
Query: "sparse matrix factorization"  
Snippet: "The scipy.sparse.linalgecomposition of sparse matrices is available in scipy.sparse.linalg."  

Question for ChatGPT:  
"Is this snippet relevant to the query? Answer Yes or No, and provide a one-sentence justification."  
```

Make a table and include all the query/snippet/ChatGPT outputs.ses sparse LU factorization, which is one form of sparse matrix factorization.*
```

---

### 4. Summarize Findings

Reflect on your observations. Consider the following guiding questions:

**Query length:** How long should a query be to get useful results? Did shorter keyword queries work as well as longer, descriptive ones?

**Documentation coverage:** Were some parts of the SciPy documentation more complete than others? How did that affect retrieval quality?

**Exact vs. fuzzy matching:** Did you need to match words exactly (e.g., `"LU decomposition"` vs. `"factorization"`) to get good results? Give one example where exact matching was not required, and one where it failed.

**Variation across query types:** Which query styles (conceptual, API-specific, natural language, edge cases) gave the most helpful results? Which tended to misfire?

**Role of ChatGPT:** How reliable was ChatGPT as a relevance judge? Did it agree with other methods, such as manual check, ChatGPT check, notes)?

### Questions for Discussion

* Why might we use **different models** for code and for documentation?
* Why might we choose **different chunk lengths** for code vs. docs?
* What are the potential **advantages or trade-offs** of alternative strategies?

*In your answers, consider the task requirements, the size of the corpus, and the amount of compute available (especially when using free models).*
"""

import pandas as pd
import json
# use query_index to make a query
# query_index(query, topk, code_or_doc)
query_concept = 'b-splines in signal processing'
query_function = 'scipy.linalg.kron'
query_keyword = 'univariate interpolation'
query_natural_lang = 'How do I perform nonlinear least squares for a set of points in SciPy?'
query_edge_case = 'Vorini diagrems'

query_list = [query_concept, query_function, query_keyword, query_natural_lang, query_edge_case]
results = []
# make the queries
for it, (query) in enumerate(query_list):
  top_result_idx = query_index(query,topk=1,code_or_doc='docs')[0]
  with open("docs/chunks_metadata.json",'r') as chunks:
    results.append(json.loads(list(chunks)[top_result_idx])["text"])
# make and save results in a dataframe
df = pd.DataFrame({
    'Query': query_list,
    'Result': results
})

df

# use dataframe to check for alignment
alignment = [1,0,1,0,1]
df['Aligned'] = alignment

# ChatGPT as relevance judge
chatgpt_yn = ['Yes','No','Yes','No','Yes']
chatgpt_explain = [
    'The snippet includes a section specifically on B-splines within the context of scipy.signal, detailing their use in signal processing tasks such as filtering and spline evaluation.',
    'The snippet concerns deprecation and internal structure of scipy.linalg.misc, and does not mention or provide information about scipy.linalg.kron.',
    'The snippet directly discusses InterpolatedUnivariateSpline, a method for performing univariate interpolation using splines, which is highly relevant to the query.',
    'The snippet discusses smoothing splines via scipy.interpolate, which solve a penalized least-squares problem, but it is not directly relevant to performing nonlinear least squares fitting using scipy.optimize.least_squares or curve_fit, which is what the query is asking about.',
    'The snippet discusses the SphericalVoronoi class and various tests involving Voronoi diagrams on a sphere, which is relevant to the (misspelled) query "Vorini diagrems" — likely intended to be "Voronoi diagrams."']
df['ChatGPT Alignment'] = chatgpt_yn
df['ChatGPT Reasoning'] = chatgpt_explain

with open('part_2_tbl.tex', 'w') as f:
  f.write(df.to_latex(index=False, caption="My DataFrame Table", label="tab:my_dataframe"))

# display dataframe
df

"""# Part 3 – Quantitative Evaluation

We now want to **measure retrieval quality** (how well relevant code/doc chunks are retrieved) and **answer quality** (how grounded the model’s response is).

---

## Precision & Recall

* **Precision\@k**: fraction of the top *k* retrieved chunks that are relevant.

  $$
  \text{Precision@k} = \frac{\# \text{ relevant chunks in top k}}{k}
  $$

* **Recall\@k**: fraction of all relevant chunks that appear in the top *k*.

  $$
  \text{Recall@k} = \frac{\# \text{ relevant chunks in top k}}{\# \text{ total relevant chunks}}
  $$

---

## How to Evaluate

1. Pick **3–5 SciPy-focused queries** (function names, error cases, natural language).
2. For each query:

   * Record the **retrieved top-k chunks**.
   * Label which chunks are **relevant** (contain the needed function/definition/example).
   * Compute precision\@k and recall\@k for k = 1, 3, 5.
   * Collect the model’s answer.
   * Assign an **answer relevance score (0/1)**:

     * **1** = grounded in retrieved code/docs,
     * **0** = hallucinated/unrelated.

---

## Example Table with SciPy Queries

| Query                                             | P\@1 | P\@3 | P\@5 | R\@5 | Answer Relevant? (0/1) | Notes                                  |
| ------------------------------------------------- | ---- | ---- | ---- | ---- | ---------------------- | -------------------------------------- |
| sparse.linalg.cg                                | 1    | 1    | 0.8  | 0.8  | 1                      | Correctly retrieved conjugate grad fn  |
| fft convolution example                        | 1    | 0.67 | 0.8  | 0.8  | 1                      | Good examples in signal.fft docs       |
| optimize.minimize with bounds                  | 1    | 1    | 1    | 1    | 1                      | Direct hit in optimization tutorial    |
| stats.ttest_ind                                 | 0    | 0.33 | 0.4  | 0.4  | 0                      | Retrieved partial, model filled in     |
| *How do I solve a sparse linear system in SciPy?* | 1    | 0.67 | 0.8  | 0.8  | 1                      | Found references to `spsolve` and `cg` |


# Free or paid? It's up to you
Given that our assessment is not very long, a free way of assessing the output is to just use the ChatGPT free interface. But, if you are so inclined, you are of course welcome to pay for the OpenAI API (e.g. `gpt-4o-mini`). It isn't very expensive, and can help you practice setting up more automated testbeds.  Here is the process for doing that:


```bash
pip install openai
```

```python
from openai import OpenAI
client = OpenAI()

def ask_llm(user_query, retrieved_chunks):
    prompt = f'''
    You are an expert on the following codebase.
    Answer the question using only the provided code context.

    Code context:
    {retrieved_chunks}

    Question:
    {user_query}

    Answer:
    '''
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role":"user","content":prompt}]
    )
    return resp.choices[0].message.content
```


"""

query_concept = 'b-splines in signal processing'
query_function = 'scipy.linalg.eig'
query_keyword = 'univariate interpolation'
query_natural_lang = 'How do I perform nonlinear least squares for a set of points in SciPy?'
query_edge_case = 'Vorini diagrems'

query_list = [query_concept, query_function, query_keyword, query_natural_lang, query_edge_case]
results = []
# make the queries
for it, (query) in enumerate(query_list):
  k_sub=[]
  top_result_idx = query_index(query,topk=5)
  print(top_result_idx)

# alignment lists that help with the precision and recall table
# done through manual checking of the chunk with the doc index
alg_concept = [1, 1, 1, 1, 1]
alg_function = [1, 1, 0, 0, 0]
alg_keyword = [1, 1, 0, 0, 1]
alg_nl = [0, 0, 1, 1, 1]
alg_ec = [0, 0, 1, 0, 0]

all_prec = [alg_concept,alg_function,alg_keyword,alg_nl,alg_ec]

notes = [
    "Nails the concept accurately.",
    "Switched to scipy.linalg.eig since scipy.linalg.kron gave very poor results.",
    "Gets the overarching theme of the operation, but not the operation itself.",
    "Fails the first few times, then it gets the concept on later results.",
    "Cannot overcome the spelling errors in 'Voronoi diagrams'."
]

# calculate precision and recall for each query for each value of k
df_prec_rec = pd.DataFrame({
    "Query": query_list,
    "P@1": [lst[0] for lst in all_prec],
    "P@3": [sum(lst[0:3])/3 for lst in all_prec],
    "P@5": [sum(lst)/5 for lst in all_prec],
    "R@1": [lst[0]/sum(lst) for lst in all_prec],
    "R@3": [sum(lst[0:3])/sum(lst) for lst in all_prec],
    "R@5": [sum(lst)/sum(lst) for lst in all_prec],
    "Answer Relevant? (0/1)": [lst[0] for lst in all_prec],
    "Notes": notes
})

with open('part_3_tbl.tex', 'w') as f:
  f.write(df_prec_rec.to_latex(index=False, caption="My DataFrame Table", label="tab:my_dataframe"))

df_prec_rec

"""# Part 4 – Adding Code Retrieval and Evaluation

Now that you have embeddings for documentation, we will extend the system to also include **code embeddings**. This will allow the retriever to pull both documentation chunks *and* code chunks when answering a query.

---

## Step 1. Train & Add Code Embeddings

1. Use the same embedding workflow as before, but now applied to **code chunks** (functions, classes, or 50–80 line segments).
2. Store these in your vector index alongside your documentation embeddings.

---

## Step 2. Qualitative Assessment (Code Only)

As you did earlier for documentation:

1. Pick **3–5 queries** that are code-oriented (e.g., function names, error messages, “how do I call X?”).
2. Retrieve the top chunks from the **code index** only.
3. Evaluate qualitatively:

   * Do the retrieved chunks contain the right functions/classes?
   * Are signatures, docstrings, and examples useful?
   * Where does it fail (e.g., missing, too long, irrelevant)?

Keep brief notes for each query.


## Step 3.  Quantitative Evaluation with Fusion

Now we want to combine results from **doc retrieval** and **code retrieval** into a single ranked list. The process is:

1. **Retrieve a large candidate pool**

   * If your original top-k was, say, `k=5`, now retrieve about `10×k` (e.g., 50) from *each* index (docs and code).
   * This ensures you don’t miss relevant results that would otherwise be cut off.

2. **Compute fusion scores**

   * **Reciprocal Rank Fusion (RRF):**

     $$
     \text{RRF}(d) = \sum_{i \in \{\text{doc, code}\}} \frac{1}{k_0 + \text{rank}_i(d)}, \quad k_0 \in [60,100]
     $$

     This combines the rankings from both sources.
   * **(Optional)** Instead of RRF, you can use a **weighted similarity score**:

     $$
     \text{score}(d) = 0.6 \cdot \text{score}_{\text{code}}(d) + 0.4 \cdot \text{score}_{\text{doc}}(d)
     $$

     Use this if your queries are often function- or symbol-heavy.

3. **Re-rank and select final top-k**

   * After computing scores for all candidates, sort them.
   * Keep the best `k` (e.g., 5) as your fused retrieval output.



## Step 4. Build Your Evaluation Table

As before, compute **Precision\@k** and note whether the **answer is grounded**. This time evaluate both fused retrieval methods (RRF and/or weighted sum).

| Query                                      | P\@1 | P\@3 | P\@5 | Answer Relevant? (0/1) | Notes                                               |
| ------------------------------------------ | ---- | ---- | ---- | ---------------------- | --------------------------------------------------- |
| `sparse.linalg.cg`                         | 1    | 1    | 0.8  | 1                      | Found correct function signature                    |
| `fft convolution example`                  | 1    | 0.67 | 0.8  | 1                      | Docs + code both retrieved                          |
| *How do I solve a sparse system in SciPy?* | 1    | 0.67 | 0.8  | 1                      | Fused retrieval covered both `spsolve` and tutorial |



"""

import pandas as pd
import json
# use query_index to make a query
# query_index(query, topk, code_or_doc)
query_concept = 'b-splines in signal processing'
query_function = 'scipy.linalg.kron'
query_keyword = 'univariate interpolation'
query_natural_lang = 'How do I perform nonlinear least squares for a set of points in SciPy?'
query_edge_case = 'Vorini diagrems'

query_list = [query_concept, query_function, query_keyword, query_natural_lang, query_edge_case]
results = []
# make the queries
for it, (query) in enumerate(query_list):
  top_result_idx = query_index(query,topk=1,code_or_doc='code')[0]
  with open("code/chunks_metadata.json",'r') as chunks:
    results.append(json.loads(list(chunks)[top_result_idx])["text"])
# make and save results in a dataframe
df = pd.DataFrame({
    'Query': query_list,
    'Result': results
})

alignment = [1,0,1,0,1]
df['Aligned'] = alignment

with open('part_2_tbl.tex', 'w') as f:
  f.write(df.to_latex(index=False, caption="My DataFrame Table", label="tab:my_dataframe"))

# display dataframe
df

def fused_retrieval(query, k=5, k0=60):
  # typically used k0=60 for best performance
  code_list=query_index(query, topk=10*k, code_or_doc = 'code')
  doc_list=query_index(query, topk=10*k, code_or_doc = 'docs')
  all_scores = []
  for chunk_idx in set(code_list).union(set(doc_list)):
    # store index for later retrieval
    code_idx = np.where(code_list==chunk_idx)[0] if chunk_idx in code_list else -1
    doc_idx = np.where(doc_list==chunk_idx)[0] if chunk_idx in doc_list else -1
    # create each term for the summation in the RRF formula
    code_term = 1/(k0+code_idx) if code_idx != -1 else 0
    doc_term = 1/(k0+doc_idx) if doc_idx!= -1 else 0
    rrf = code_term + doc_term
    # make a tuple list with the chunk index, rrf, index in code doc, index in doc list
    all_scores.append((int(chunk_idx), float(rrf), int(code_idx!=-1), int(doc_idx!=-1)))
  # now sort the scores by rrf
  return sorted(all_scores, key=lambda elem: elem[1], reverse=True)[0:k]

query_concept = 'b-splines in signal processing'
query_function = 'scipy.linalg.eig'
query_keyword = 'univariate interpolation'
query_natural_lang = 'How do I perform nonlinear least squares for a set of points in SciPy?'
query_edge_case = 'Vorini diagrems'

query_list = [query_concept, query_function, query_keyword, query_natural_lang, query_edge_case]
results = []
# make the queries based upon RRF
for it, (query) in enumerate(query_list):
  k_sub=[]
  top_result_idx = fused_retrieval(query,k=5)
  print(top_result_idx)

# 1 if it is in the doc, 0 otherwise

# I keep getting index out of error when automating the load and retrieval step
# Manually retrieve the chunks per query and determine the alignment of each
mode='docs'
with open(f"{mode}/chunks_metadata.json",'r') as chunks:
  df = pd.DataFrame({
      "query": [query_edge_case],
      "txt": [json.loads(list(chunks)[5])["text"]]
      })
df

# manually make the table based upon the chunk indices returned
# alignment lists that help with the precision and recall table
alg_concept = [1, 1, 1, 1, 1]
alg_function = [1, 1, 1, 0, 1]
alg_keyword = [1, 1, 1, 1, 0]
alg_nl = [0, 1, 1, 1, 1]
alg_ec = [1, 0, 0, 0, 0]

all_prec = [alg_concept,alg_function,alg_keyword,alg_nl,alg_ec]

notes = [
    "Retrieves more relevant results than before with more mentions of b-splines.",
    "Gives more pertinent use cases of scipy.linalg.eig.",
    "Gives more examples of univariate interpolation.",
    "Gives more language examples of how to do the operation.",
    "Does not perform well with spelling errors."
]

# calculate precision and recall for each query for each value of k
df_prec_rec = pd.DataFrame({
    "Query": query_list,
    "P@1": [lst[0] for lst in all_prec],
    "P@3": [sum(lst[0:3])/3 for lst in all_prec],
    "P@5": [sum(lst)/5 for lst in all_prec],
    "Answer Relevant? (0/1)": [lst[0] for lst in all_prec],
    "Notes": notes
})

with open('part_4_tbl.tex', 'w') as f:
  f.write(df_prec_rec.to_latex(index=False, caption="My DataFrame Table", label="tab:my_dataframe"))

df_prec_rec

